version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # 프론트엔드에 해당하는 Dockerfile
    ports:
      - "3000:3000"  # 호스트의 3000 포트를 컨테이너의 3000 포트에 매핑
    environment:
      - REACT_APP_API_URL=http://backend:5000  # 백엔드 API URL
    volumes:
      - .:/app  # 로컬 소스 코드와 컨테이너 공유
    command: npm start  # 애플리케이션 시작 명령어
